- .dockerignore
- .gitignore
- Dockerfile
- Makefile
- docker-compose.yml
- truffle.js
Taking a stab at setting up docker-compose for the Dapp. Followed some of the `docker-compose.yml` setup found at https://github.com/MarketProject/MarketProtocol
* Now allows for you to get started with your dev environment by typing `docker-compose up`
* Keeps everything self-contained. You don't even need to install truffle on your machine now.
* No node_modules on your host machine
* If you do have truffle installed on your machine, you can access the network setup by the truffle container with `truffle console --network development`
* react app still auto rebuilds whenever you change files locally
* Migration still has to be done manually. I added a Makefile so that it's as easy as `make docker_migrate`. Def open to alternatives here.
* Adding new deps requires the Docker image to be …
> Dockerfile plus docker-compose setup

- src/components/DeployContractField.js
Fixes https://github.com/MarketProject/Dapp/issues/14
Change causes both `priceCap` and `priceFloor` fields to be validated at the same time when one of them changes.
> Price cap and price floor validate together

- src/components/DeployContractForm.js
- src/components/DeployContractSuccess.js
Closes https://github.com/MarketProject/Dapp/issues/15
Clicking on the url takes you to the etherscan page for the contract address (obviously, will be most helpful when this is deployed to mainnet).
If we think the link isn't a good idea, I can get rid of it. We could also do other things like make so if you click the link, instead of taking you to etherscan, it'd copy the address to your clipboard or something.
> Adding contract address to deploy message

- src/actions/deploy.js
When dispatching the "DEPLOY_CONTRACT_FULFILLED" event, the payload should be the market contract instance that we just deployed to the blockchain. Seem reasonable?
> Use the deployed instance as contract payload

- src/components/DeployContract/DeployContractField.js
- src/components/Step.css
- src/components/TestQuery/OracleDataSources.js
- src/components/TestQuery/Steps.js
Current copy was a bit hard to read.
- Reworked the `sampleQueries` array to include objects with `query` and `title`.
- Output the `sampleQueries` array to new `.sample-query-list` element.
#43
> Added styling for sample query list

- src/components/DeployContract/GuidedDeployment.js
- src/components/DeployContract/Steps.js
Steps for the Guided Contract Deployer should be modified / reorganized to move the data source closer to naming and before worrying about pricing
Reorder the `<Steps...` component and add proper 'next' buttons.
#46
> Reorder deployment steps

- src/actions/testQuery.js
- src/containers/TestQuery.js
If an error occurs from the providers (for example rejecting the transation from metamask), this PR ensure the error is caught and displayed to the user.
>  Add error handler for errors during testOracleQuery request

- src/App.css
- src/Splash.js
- src/components/ContractsList.js
- src/components/DeployContract/DeployContractField.js
- src/components/DeployContract/QuickDeployment.js
- src/components/FindContract/FindContractForm.js
- src/components/Landing.css
- src/components/Landing.js
- src/components/Loader.js
- test/components/Loader.test.js
- Added ‘showInCenterOfPage’ props to place the loader in centre of page
- Replaced tooltips with popovers in QuickDeploy page
- Fixed ‘NaN’ showing up in initial value of input fields in
QuickDeploy page
> Fixed issues #63 and #64

- src/util/web3/getWeb3.js
- test/util/web3/getWeb3.test.js
Fixes: #111
Fixes MetaMask detection by using async versions of accounts and network.
web3 init
Tested manually.
Fixes: #111
> Fix for [General] "MetaMask is Locked" error message: Use async functions for accounts and network.

- src/actions/deploy.js
- src/actions/testQuery.js
- src/util/utils.js
- test/actions/deploy.test.js
- test/util/utils.test.js
Errors thrown by MetaMask contain a summary and a detailed stack trace follows.
Pass only the summary to the error payload to be displayed in case an error occurs.
The change is quite safe. In case the error message consists of only one line, the full error message be shown.
actions
Tested manually.
Fixes: #116
> Fixes #116: actions/deploy,testQuery: Refine error messages.

- src/components/DeployContract/GuidedDeployment.js
- src/components/DeployContract/Steps.js
- src/components/TestQuery/Steps.js
- src/components/TestQuery/TestQueryForm.js
- test/components/DeployContract/GuidedDeployment.test.js
- test/components/TestQuery/TestQueryForm.test.js
Add button to restart the process of test query in case of failure
Button with consistent design.
fixes #115
> Add back button in case of error on test query or error on sumitting a contract

- src/components/DeployContract/QuickDeployment.js
- src/less/App.less
- test/components/DeployContract/QuickDeployment.test.js
Add an overlay while is waiting network response when one contract is deployed.
Fixes: #110
> Add overlay when 'quick deploy contract' is waiting for a response

- src/less/Header.less
This PR prevents logo truncation by updating media queries to rely on accurate absolute pixel widths. The design of the header could probably be further refined by keeping it at a single width and displaying only the most important items plus an overflow menu, but I've stayed within the scope of the issue.
N/A
This is a simple CSS change, so I tested by opening in the latest Chrome, Firefox, and Safari.
Fixes: #118
> fix header logo sizing to prevent truncation

- src/components/DeployContract/DeployContractField.js
- test/components/DeployContract/DeployContractForm.test.js
- test/components/DeployContract/QuickDeployment.test.js
Disables dates more than 60 days from today in the expiration date picker. Also disables past days as it doesn't make sense.
UI
Performed QA to make sure it works as expected.
Fixes #142
> Ensure expiration timestamp cannot be more than 60 days from today

- README.md
- package.json
Adds control of the version of Node.js to gaurentee compatibility
Node Version
Tested with make run_tests
Fixes: #121
> adds Node ^8.11.2 to engines and readme

- src/components/DeployContract/QuickDeployment.js
- test/components/DeployContract/QuickDeployment.test.js
Removes 'Reset Form' button on Quick deployment form. Also removes the test related to it.
UX
Fixes #217
> Remove reset button in quick deployment form

- src/components/DeployContract/ExchangeSources.js
- src/components/DeployContract/SelectTokenField.js
- test/components/DeployContract/SelectTokenField.test.js
Simplified Deploy
Local
Fixes: #229
> Extend Simplified Deploy to include Bitfinex API

- src/components/DeployContract/Steps.js
- This PR resolve a bug when calendar is initialized from DatePicker react component.
- I have passed `null` instead of empty string for resolve the issue.
- Maybe there are another methods to resolve it but i wanted to change as little as possible the logic.
Component Bug
- I have tested this change in local, using Developer Branch.
- Mac OS 
Fixes: #287
> fix issue #287 calendar initial value invalid type

- src/components/SimExchange/OrderBook/Columns.js
- src/components/SimExchange/OrderBook/Orders.js
- src/components/SimExchange/OrdersPositionsFills/Index.js
- src/components/SimExchange/OrdersPositionsFills/OpenOrders.js
- src/components/SimExchange/OrdersPositionsFills/Positions.js
- src/components/SimExchange/TradeHistory/Columns.js
- src/components/SimExchange/TradeHistory/Trades.js
- src/components/SimExchange/Wallet.js
- src/components/SimExchange/Wallet/Table.js
- src/less/SimExchange.less
- Hiding scrollbars for WebKit browsers in sim exchange to fix showing up of defauly ugly scrollbars in windows and other environments
- Setting scroll height for tables
- Removed pagination numbers for tables
UI
Tested on windows chrome browser via browserstack
Fixes: #311
> Hiding scrollbars in Simulated exchange page

- README.md
When facing module not found errors, running this command fixes them, needs to be run only once for
new containers.
Docs
Fixes: #283
> Add `docker_migrate` to README

- src/components/DeployContract/DeployContractField.js
- src/components/SimExchange/Trade/Form.js
- test/components/DeployContract/QuickDeployment.test.js
Simple changes to the DatePicker in both the DeploytContractField and SimExchange/Trade to allow the option to pick the current day for the expiration date.  When the current date is selected it will push the TimePicker pat of the DatePicker 60 minutes ahead so the user will not get a warning that the time is not valid.  
Ui/UX - DatePicker
I have tested this in my own development environment using the Rinkeby Test Network and submitted the results on a development server
Fixes: https://github.com/MARKETProtocol/dApp/issues/300
> [Date Picker] Fixed issue selecting current day

- src/actions/explorer.js
- src/util/contracts.js
- src/util/marketAPI.js
- test/actions/explorer.test.js
- test/util/marketAPI.test.js
This PR deprecates the get whitelisted address API and replaces it with the new API calls.
It also removes the caching done when loading transaction through web3 (no more needed)
MarketAPI
Fixes: #332
> Deletes and replaces API WhitelistedAddress calls with Contracts path
