package-lock.json, package.json, src/actions/deploy.js, src/actions/explorer.js, src/components/ContractsList.js, src/components/DeployContractField.js, src/components/DeployContractForm.js
I realized the variable name was very confusing for it's inteneded function.  This PR updates the `market-solidity` package to 0.0.5 and refactors all references to the variable 
@poffdeluxe - found this when writing explanations for the contract deployer which are also included.
Everything seems to be working.
=> refactoring QTY_DECIMAL_PLACES to QTY_MULTIPLIER

src/components/DeployContract/DeployContractField.js
Fixes https://github.com/MarketProject/Dapp/issues/41
Also, negative numbers aren't accepted (Min is 0 on the input)
=> price floor/cap must be integers

src/components/DeployContract/DeployContractField.js, src/components/TestQuery/Steps.js, test/components/DeployContract/QuickDeployment.test.js
Fixes the warnings and also resolves #40 .
=> Fix warning and ethAddress Validator bug

src/components/DeployContract/DeployContractForm.js, src/components/DeployContract/QuickDeployment.js
Enables setting quick deployment fields from url query params.
=> Preset quick deployment fields

migrations/2_deploy_contracts.js, package-lock.json, package.json, src/actions/deploy.js, src/components/DeployContract/DeployContractField.js, src/components/DeployContract/GuidedDeployment.js, src/components/DeployContract/QuickDeployment.js, src/components/DeployContract/Steps.js
Currently the first query from oraclize.it is free - we can right now get away with not paying anything into the contract to start.
=> Remove pre-funding needs

migrations/2_deploy_contracts.js, package-lock.json, package.json, src/actions/deploy.js, src/actions/explorer.js, src/components/ContractsList.js
this updated to the latest `market-solidity` and fixes some gas issues around deployment.
=> Market solidity update

package-lock.json, package.json
small updates we should merge and then I will get this deployed to rinkeby for some more testing.
=> Update market solidity and open-zeppelin

src/actions/testQuery.js
modify transaction to exact cost of query rather than currently hard coded value 
Fixes: #99
=> [WIP] modify transaction to exact cost of query rather than currently hard coded value 

src/actions/find.js, src/components/DeployContract/DeployContractField.js, src/util/utils.js, src/util/validations.js, test/util/validations.test.js
Validation on the smart contract : Valid smart contract address or not
Fixes: #78 
Fixes: #80
=> ISSUE 78 with tests

src/components/FindContract/FindContractField.js, src/components/FindContract/FindContractForm.js, src/containers/Find.js, src/util/forms/Validators.js, test/components/FindContract/FindContractField.test.js, test/components/FindContract/FindContractForm.test.js, test/components/FindContract/FindContractSuccess.test.js, test/util/forms/Validators.test.js, test/util/utils.test.js
Tests for Find Contract Components
It also Includes refactoring of some components for clarity and tests for some utility functions.
Tests
Wrote some tests to check for stability and also tested physically.
=> Tests for Find Contract Component

src/components/DeployContract/DeployContractField.js, src/components/DeployContract/QuickDeployment.js, src/util/validations.js, test/util/validations.test.js
Validate ERC20 contract based on the address bytecode
Add inline style overflow-x hidden in QuickDeployment form to remove annoying scroll-x
Utils
Pass
Fixes: #128
=> Fixes: https://github.com/MARKETProtocol/dApp/issues/128

src/components/GasPriceField.js
Cancel ajax call on componentWillUnmount to fix console warning
No
Yes
Fixes: #131
=> [GasPriceField] Fixed the console warning

package.json, src/actions/simExchange.js, src/components/SimExchange/SimExchange.js, src/containers/SimExchange.js, src/util/utils.js, test/actions/simExchange.test.js, test/components/SimExchange/SimExchange.test.js, test/components/SimExchange/Trades.test.js, test/components/SimExchange/Wallet.test.js, test/mocks/contracts.js, test/reducers/simExchange.test.js
This is the start of the unit tests for #125. I don't see much point in getting the component coverage very high since they are in infant stages but I will work on the reducers and actions tomorrow!
Fixes: #125
=> Sim Exchange Unit Tests

src/components/DeployContract/DeployContractField.js, src/components/DeployContract/SelectTokenField.js, src/components/DeployContract/SimplifiedDeployment.js, src/components/DeployContract/Steps.js, test/components/DeployContract/Steps.test.js
UI
Manual tests only so far, but still work in progress
Fixes: #164
=> [Simplified Deploy Contract] Updated Price Floor and Price Cap

package.json, src/actions/deploy.js, src/actions/testQuery.js, src/components/DeployContract/DeployContractForm.js, src/components/DeployContract/GuidedDeployment.js, src/components/DeployContract/QuickDeployment.js, src/components/DeployContract/SimplifiedDeployment.js, src/components/DeployContract/Steps.js, src/components/GasPriceField.js, src/components/TestQuery/Steps.js, src/components/TestQuery/TestQueryForm.js, src/containers/Deploy.js, src/containers/TestQuery.js, src/less/App.less, src/reducers/deploy.js, src/reducers/testQuery.js, src/util/utils.js, test/actions/deploy.test.js, test/components/DeployContract/Steps.test.js, test/components/GasPriceField.test.js, test/components/TestQuery/Steps.test.js, test/components/TestQuery/TestQueryForm.test.js
=> Initial commit for removing hard-coded gas limit

src/components/FindContract/FindContractForm.js
Fixes the unintended horizontal overflow in Find Contract page
UI
Tested
Fixes #175
=> Fix horizontal overflow in Find Contract page

src/less/App.less
Makes it easier to read links in message boxes
UI, UX
Old:
New:
Fixes: #127
=> changes color of link

src/components/DeployContract/ExchangeSources.js, src/components/DeployContract/SelectTokenField.js, src/components/DeployContract/SimplifiedDeployment.js, src/util/utils.js, test/util/utils.test.js
SimplifiedDeployment
Local
Fixes: #188
=> Extend simplified deployment to allow for assets denominated in USDT

src/components/Header.js
Issue 191
- [x ] Changes don't break existing behavior
- [x ] Tests coverage hasn't decreased
header.js
wouldn't be able to tell from screen shot
it's a small change :)  Just saving state for the menu items.  I also made it a bit easier to add menu items by separating them into a list that gets mapped over in the render function.
=> fix for issue 191

src/less/App.less
Remove page min-height
Fixes #195
=> adjust space between footer and body

.travis.yml, scripts/clean_bucket.sh
Add script for clearing s3 bucket prior to deployment and than on production, invalidates the cloudfront cache. 
Travis, deployment, s3, cloudfront
=> add bucket cleanup and cloudfront invalidation script

src/components/DeployContract/DeployContractField.js, src/less/App.less, test/components/DeployContract/QuickDeployment.test.js
UI, UX, Tests
**BEFORE**
**AFTER**
I had tested with rinkeby and also made some visual changes for text with low contrast  (unreadable) and made some research for the UX decision.  
Fixes: #213
=> TimePicker Several bugs with selecting times for expiration

src/actions/explorer.js, src/components/SimExchange/TopBar.js, src/containers/SimExchange.js, src/util/utils.js, src/util/web3/contractInitializer.js, test/components/SimExchange/SimExchange.test.js, test/components/SimExchange/Wallet.test.js, test/util/utils.test.js
Improves loading time of contract dropdown and fixes MarketContractPool initialization error.
UX
Load SimExchange and view console that errors are clean.
=> fixes MarketContractPool error due to faulty contracts

src/actions/explorer.js, src/components/SimExchange/TopBar.js
Browse to Contract Explorer and Exchange and validate that contracts are working in both locations in the dapp.
=> compacts contracts array at top level to filter bad contracts

src/components/DeployContract/ExchangeSources.js
Update the url references to use the market-api proxy
Refs: #232
=> Updated the url references to point to the market-api proxy for Bitfinex

src/components/ContractsList.js, src/components/DeployContract/DeployContractField.js, src/components/DeployContract/Steps.js, test/components/DeployContract/Steps.test.js
Renamed all test occurrences of Base Token to Collateral token for clarity
Fixes #244
=> Replace Base Token with Collateral Token

src/components/DeployContract/PriceGraph.js, src/components/DeployContract/Steps.js, test/components/DeployContract/PriceGraph.test.js, test/components/DeployContract/Steps.test.js
I will think about tests for this tomorrow.
https://i.imgur.com/bjkVCsG.png
Fixes: #241
=> Price cap/floor graph

src/components/ContractsList.js
=> New explorer UI responsive bug

config/polyfills.js, src/util/contracts.js
=> cache contract addresses on develop

src/App.js, src/components/DeployContract/DeployContractSuccess.js, src/components/DeployContract/ExchangeSources.js, src/components/DeployContract/SelectTokenField.js, src/components/FindContract/FindContractForm.js, src/components/SimExchange/SimExchange.js, src/components/SimExchange/Trades.js, src/components/SimExchange/WalletComponents/HeaderMenu.js, src/components/SimExchange/WalletComponents/Table.js, src/components/TestQuery/TestQueryForm.js, src/components/TestQuery/TestQuerySuccess.js, src/util/contracts.js
=> Updates React lifecycle methods

src/components/ContractsList.js
Makes it so that selecting a token only returns that token and not tokens that have partial matches.
Fixes: #284
=> Token filters are now exact match

package-lock.json, package.json, src/util/marketjs/marketMiddleware.js
Upgraded `MARKET.js` to `v0.2.2`
`marketMiddleware.js`
Fixes: #273
=> Upgraded MARKET.js to 0.2.2

src/util/utils.js, test/util/utils.test.js
This PR aims to increase the coverage of `/src/util/utils.js` to 100% by adding tests.
Tests
Fixes https://github.com/MARKETProtocol/dApp/issues/281
=> Increase code coverage for Utils

src/components/ContractsList.js, src/components/SimExchange/SimExchange.js, src/components/SimExchange/TopBar.js, src/components/SimExchange/Trade/Trades.js, src/components/SimExchange/TradeHistory/Trades.js, src/routes.js, src/util/marketjs/marketMiddleware.js
=> Trade History

src/components/SimExchange/OrdersPositionsFills/Index.js, src/components/SimExchange/OrdersPositionsFills/Positions.js, src/components/SimExchange/SimExchange.js, src/util/marketjs/marketMiddleware.js, test/util/marketjs/marketMiddleware.test.js
=> A users positions for a specific MARKET contract

src/components/DeployContract/DeployContractField.js, src/components/DeployContract/SelectTokenField.js, src/components/DeployContract/SimplifiedDeployment.js, src/components/DeployContract/Steps.js, src/components/Header.js, src/less/Step.less, test/components/DeployContract/SimplifiedDeployment.test.js
- Removed Quick and Guided Deploy flow from Navbar
- Added `Contract Name` step to add user input text
Fixes: #270
=> Initial commit for standardizing contract name

src/components/SimExchange/Wallet.js, src/components/SimExchange/Wallet/HeaderMenu.js, src/less/App.less, src/less/SimExchange.less, src/less/SimExchange/Wallet.less
Truncating 'Available to Deposit' amount to 2 decimal digits. 
UI
Tested briefly
Fixes #310
=> Truncating 'Available to Deposit' amount to 2 decimal digits in wallet section of Sim exchange

src/components/ContractsList.js, src/components/DeployContract/Steps.js, src/less/App.less
=> Fixed UI/UX issues in Contracts Explorer

src/components/ContractsList.js, src/components/SimExchange/SimExchange.js, src/components/SimExchange/Trade/Trades.js, src/components/SimExchange/Wallet/Columns.js, src/components/SimExchange/Wallet/HeaderMenu.js, src/components/SimExchange/Wallet/Table.js, src/less/App.less, src/less/ContractsList.less, src/less/MarketTheme.less, src/less/SimExchange.less, src/util/marketjs/marketMiddleware.js, src/util/utils.js, test/util/utils.test.js
Updated the UI of wallet history tab based on the new designs
UI
Fixes: #339
=> Modified Wallet history UI in sim exchange

package-lock.json, package.json
=> upgrades dapp to abi 0.0.3
